##*************************************************************************************##
# Navigation control message                                                            #
# This contains information to send to the joystick to manuevre the drive system.       #
# * x_input: joystick x_input for horizontal movement                                   #
# * y_input: joystick y_input for vertical movement                                     #
##*************************************************************************************##

Header header

geometry_msgs/Twist cmd_vel